/// Flutter icons Esportes
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Esportes
///      fonts:
///       - asset: fonts/Esportes.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Esportes {
  Esportes._();

  static const _kFontFam = 'Esportes';
  static const _kFontPkg = null;

  static const IconData futebol = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData corre = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alvo = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basquetebol = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soccer_ball = IconData(0xf1e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
